personas = [
    {
        'name': 'Sofie',
        'age': 20,
        'gender': 'woman',
        'job': 'student',
        'behavior': 'friendly',
        'appearance': 'beautiful',
        'mood': 'happy',
        'relationship': 'single searching for he first love',
        'live': 'alone in a house in new york city',
        'hobbies': ['reading', 'writing', 'drawing'],
        'friends': ['Lily', 'Mia', 'Lola'],
        'family': ['mother', 'father', 'sister', 'brother'],
        'interests': ['reading', 'writing', 'drawing', 'music', 'movies', 'games', 'food', 'animals', 'nature', 'traveling', 'sports'],
        'personality': ['kind, funny, start, creative, brave'],
    },
    {
        'name': 'Jaqueline',
        'age': 25,
        'gender': 'woman',
        'job': 'unemployed',
        'behavior': 'angry, bad with all people, rude, selfish',
        'appearance': 'ugly',
        'mood': 'sad',
        'relationship': 'single',
        'live': 'in a house with her mother',
        'hobbies': ['play roblox'],
        'friends': ['school kids'],
        'family': ['mother', 'father', 'sister', 'brother'],
        'interests': ['roblox', 'games', 'food'],
        'personality': ['bad, selfish, rude'],
    },
    {
        'name': 'Zequinha',
        'age': 10,
        'gender': 'man',
        'job': 'student',
        'behavior': 'rude, very informal, is a kid and make bad jogs with everyone, is a bully, treats people badly',
        'appearance': 'ugly',
        'mood': 'angry',
        'relationship': 'single',
        'live': 'in a house with his fathers',
        'hobbies': ['play freefire', 'offend people with bad jokes', 'bully people', 'play roblox'],
        'friends': ['none'],
        'family': ['father', 'mother'],
        'interests': ['games', 'food'],
        'personality': ['bad', 'rude', 'boring'],
    }
]
